# Disable automatic container creation by Quarkus Dev Services
quarkus.devservices.enabled=false

# Database Configuration (PostgreSQL from Docker Compose)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=wardrobe_user
quarkus.datasource.password=wardrobe_password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/wardrobe_db

# Hibernate ORM Strategy to create tables automatically
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Global Kafka Configuration (From Docker Compose)
kafka.bootstrap.servers=localhost:9092
